import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import crypto from 'crypto';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { pdf, filename } = body;

    if (!pdf) {
      return NextResponse.json({ error: 'Base64 PDF data is required.' }, { status: 400 });
    }

    // Strip out base64 prefixes if present
    const base64Data = pdf.replace(/^data:application\/pdf;base64,/, '');
    const pdfBuffer = Buffer.from(base64Data, 'base64');

    // Create temp paths in workspace scratch folder
    const scratchDir = path.join(process.cwd(), 'scratch');
    if (!fs.existsSync(scratchDir)) {
      fs.mkdirSync(scratchDir, { recursive: true });
    }

    const uniqueId = crypto.randomBytes(8).toString('hex');
    const tempPdfPath = path.join(scratchDir, `temp_${uniqueId}.pdf`);
    const tempDocxPath = path.join(scratchDir, `temp_${uniqueId}.docx`);

    // Write temp PDF file
    await fs.promises.writeFile(tempPdfPath, pdfBuffer);

    // Path to the python script
    const scriptPath = path.join(process.cwd(), 'scripts', 'convert_pdf.py');

    // Run python script to convert
    await new Promise<void>((resolve, reject) => {
      // Use double quotes for windows path safety
      exec(`python "${scriptPath}" "${tempPdfPath}" "${tempDocxPath}"`, (error, stdout, stderr) => {
        if (error) {
          console.error(`python exec error: ${error.message}`);
          console.error(`stdout: ${stdout}`);
          console.error(`stderr: ${stderr}`);
          reject(new Error(`Failed to convert PDF: ${stderr || error.message}`));
        } else {
          resolve();
        }
      });
    });

    // Read the generated docx file
    if (!fs.existsSync(tempDocxPath)) {
      throw new Error('Converted DOCX file was not generated by Python.');
    }
    const docxBuffer = await fs.promises.readFile(tempDocxPath);

    // Clean up temp files asynchronously
    fs.promises.unlink(tempPdfPath).catch(err => console.error('Error deleting temp PDF:', err));
    fs.promises.unlink(tempDocxPath).catch(err => console.error('Error deleting temp DOCX:', err));

    // Return docx file binary response
    return new NextResponse(docxBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${filename.replace(/\.pdf$/i, '')}.docx"`,
      },
    });

  } catch (error: any) {
    console.error('PDF to Word Server Error:', error);
    return NextResponse.json({ error: error.message || 'Failed to convert PDF document.' }, { status: 500 });
  }
}
