import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import crypto from 'crypto';

const SCRIPT_PATH = path.join(process.cwd(), 'scripts', 'split_pdf.py');

function runPython(args: object, operation: string): Promise<any> {
  return new Promise((resolve, reject) => {
    const argsJson = JSON.stringify(args).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    const cmd = `python "${SCRIPT_PATH}" ${operation} "${argsJson}"`;
    exec(cmd, { maxBuffer: 100 * 1024 * 1024 }, (error, stdout, stderr) => {
      if (error) {
        reject(new Error(stderr || error.message));
      } else {
        try {
          // Python outputs progress to stderr, result JSON is the last line on stdout
          const lastLine = stdout.trim().split('\n').pop() || '{}';
          resolve(JSON.parse(lastLine));
        } catch {
          resolve({});
        }
      }
    });
  });
}

export async function POST(request: NextRequest) {
  const scratchDir = path.join(process.cwd(), 'scratch');
  if (!fs.existsSync(scratchDir)) fs.mkdirSync(scratchDir, { recursive: true });

  const uniqueId = crypto.randomBytes(8).toString('hex');
  const tempPdfPath = path.join(scratchDir, `split_input_${uniqueId}.pdf`);
  const tempOutputDir = path.join(scratchDir, `split_output_${uniqueId}`);

  try {
    const body = await request.json();
    const { pdf, filename, mode, ranges, fixedInterval, mergeRanges } = body;

    if (!pdf) {
      return NextResponse.json({ error: 'Base64 PDF data is required.' }, { status: 400 });
    }

    const base64Data = pdf.replace(/^data:application\/pdf;base64,/, '');
    const pdfBuffer = Buffer.from(base64Data, 'base64');
    await fs.promises.writeFile(tempPdfPath, pdfBuffer);
    fs.mkdirSync(tempOutputDir, { recursive: true });

    // Python script handles split + zipping internally
    const result = await runPython({
      pdf_path: tempPdfPath,
      output_dir: tempOutputDir,
      mode: mode || 'range',
      ranges: ranges || [],
      fixed_interval: fixedInterval || 1,
      merge_ranges: mergeRanges || false,
    }, 'split');

    const resultPath: string = result.result_path || '';
    const isZip: boolean = result.is_zip || false;

    if (!resultPath || !fs.existsSync(resultPath)) {
      throw new Error('No output file was generated by the split operation.');
    }

    const resultBuffer = await fs.promises.readFile(resultPath);
    const baseName = (filename || 'document').replace(/\.pdf$/i, '');
    const contentType = isZip ? 'application/zip' : 'application/pdf';
    const downloadName = isZip ? `${baseName}_split_pages.zip` : `${baseName}_split.pdf`;

    // Cleanup all temp files async
    fs.promises.unlink(tempPdfPath).catch(() => {});
    fs.promises.unlink(resultPath).catch(() => {});
    fs.promises.rm(tempOutputDir, { recursive: true, force: true }).catch(() => {});

    return new NextResponse(new Uint8Array(resultBuffer), {
      status: 200,
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${downloadName}"`,
      },
    });

  } catch (error: any) {
    // Cleanup on error
    try { fs.unlinkSync(tempPdfPath); } catch {}
    try { fs.rmSync(tempOutputDir, { recursive: true, force: true }); } catch {}
    console.error('Split PDF Error:', error);
    return NextResponse.json({ error: error.message || 'PDF split failed.' }, { status: 500 });
  }
}

// GET page count and first-N thumbnails
export async function PUT(request: NextRequest) {
  const scratchDir = path.join(process.cwd(), 'scratch');
  if (!fs.existsSync(scratchDir)) fs.mkdirSync(scratchDir, { recursive: true });

  const uniqueId = crypto.randomBytes(8).toString('hex');
  const tempPdfPath = path.join(scratchDir, `thumb_input_${uniqueId}.pdf`);

  try {
    const body = await request.json();
    const { pdf, pages } = body;

    if (!pdf) {
      return NextResponse.json({ error: 'Base64 PDF is required.' }, { status: 400 });
    }

    const base64Data = pdf.replace(/^data:application\/pdf;base64,/, '');
    await fs.promises.writeFile(tempPdfPath, Buffer.from(base64Data, 'base64'));

    // Get page count
    const countResult = await runPython({ pdf_path: tempPdfPath }, 'count');
    const totalPages: number = countResult.total_pages || 0;

    // Render thumbnails for requested pages (max 20)
    const pagesToRender: number[] = (pages || []).slice(0, 20);
    const thumbs: Record<number, string> = {};

    for (const pageNum of pagesToRender) {
      const thumbPath = path.join(scratchDir, `thumb_${uniqueId}_p${pageNum}.png`);
      try {
        await runPython({ pdf_path: tempPdfPath, page_number: pageNum, thumb_path: thumbPath }, 'thumbnail');
        if (fs.existsSync(thumbPath)) {
          const imgBuffer = await fs.promises.readFile(thumbPath);
          thumbs[pageNum] = `data:image/png;base64,${imgBuffer.toString('base64')}`;
          fs.promises.unlink(thumbPath).catch(() => {});
        }
      } catch (thumbErr) {
        console.error(`Thumbnail error for page ${pageNum}:`, thumbErr);
      }
    }

    fs.promises.unlink(tempPdfPath).catch(() => {});
    return NextResponse.json({ totalPages, thumbs });

  } catch (error: any) {
    try { fs.unlinkSync(tempPdfPath); } catch {}
    console.error('PDF info error:', error);
    return NextResponse.json({ error: error.message || 'Failed to read PDF.' }, { status: 500 });
  }
}
