import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import crypto from 'crypto';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { excel, filename } = body;

    if (!excel) {
      return NextResponse.json({ error: 'Base64 Excel data is required.' }, { status: 400 });
    }

    // Strip out base64 prefixes if present
    const base64Data = excel.replace(/^data:application\/vnd\.(openxmlformats-officedocument\.spreadsheetml\.sheet|ms-excel);base64,/, '');
    const excelBuffer = Buffer.from(base64Data, 'base64');

    // Create temp paths in workspace scratch folder
    const scratchDir = path.join(process.cwd(), 'scratch');
    if (!fs.existsSync(scratchDir)) {
      fs.mkdirSync(scratchDir, { recursive: true });
    }

    const uniqueId = crypto.randomBytes(8).toString('hex');
    const fileExt = filename.endsWith('.xls') ? 'xls' : 'xlsx';
    const tempExcelPath = path.join(scratchDir, `temp_${uniqueId}.${fileExt}`);
    const tempPdfPath = path.join(scratchDir, `temp_${uniqueId}.pdf`);

    // Write temp Excel file
    await fs.promises.writeFile(tempExcelPath, excelBuffer);

    // Path to the python script
    const scriptPath = path.join(process.cwd(), 'scripts', 'convert_excel_to_pdf.py');

    // Run python script to convert
    await new Promise<void>((resolve, reject) => {
      exec(`python "${scriptPath}" "${tempExcelPath}" "${tempPdfPath}"`, (error, stdout, stderr) => {
        if (error) {
          console.error(`python exec error: ${error.message}`);
          console.error(`stdout: ${stdout}`);
          console.error(`stderr: ${stderr}`);
          reject(new Error(`Failed to convert Excel: ${stderr || error.message}`));
        } else {
          resolve();
        }
      });
    });

    // Read the generated PDF file
    if (!fs.existsSync(tempPdfPath)) {
      throw new Error('Converted PDF file was not generated by Python.');
    }
    const pdfBuffer = await fs.promises.readFile(tempPdfPath);

    // Clean up temp files asynchronously
    fs.promises.unlink(tempExcelPath).catch(err => console.error('Error deleting temp Excel:', err));
    fs.promises.unlink(tempPdfPath).catch(err => console.error('Error deleting temp PDF:', err));

    // Return PDF file binary response
    const downloadName = filename.replace(/\.(xlsx|xls)$/i, '') + '.pdf';
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${downloadName}"`,
      },
    });

  } catch (error: any) {
    console.error('Excel to PDF Server Error:', error);
    return NextResponse.json({ error: error.message || 'Failed to convert Excel document.' }, { status: 500 });
  }
}
