import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import crypto from 'crypto';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { docx, filename } = body;

    if (!docx) {
      return NextResponse.json({ error: 'Base64 DOCX data is required.' }, { status: 400 });
    }

    // Strip out base64 prefixes if present
    const base64Data = docx.replace(/^data:application\/vnd\.openxmlformats-officedocument\.wordprocessingml\.document;base64,/, '');
    const docxBuffer = Buffer.from(base64Data, 'base64');

    // Create temp paths in workspace scratch folder
    const scratchDir = path.join(process.cwd(), 'scratch');
    if (!fs.existsSync(scratchDir)) {
      fs.mkdirSync(scratchDir, { recursive: true });
    }

    const uniqueId = crypto.randomBytes(8).toString('hex');
    const tempDocxPath = path.join(scratchDir, `temp_${uniqueId}.docx`);
    const tempPdfPath = path.join(scratchDir, `temp_${uniqueId}.pdf`);

    // Write temp DOCX file
    await fs.promises.writeFile(tempDocxPath, docxBuffer);

    // Path to the python script
    const scriptPath = path.join(process.cwd(), 'scripts', 'convert_word_to_pdf.py');

    // Run python script to convert
    await new Promise<void>((resolve, reject) => {
      exec(`python "${scriptPath}" "${tempDocxPath}" "${tempPdfPath}"`, (error, stdout, stderr) => {
        if (error) {
          console.error(`python exec error: ${error.message}`);
          console.error(`stdout: ${stdout}`);
          console.error(`stderr: ${stderr}`);
          reject(new Error(`Failed to convert DOCX: ${stderr || error.message}`));
        } else {
          resolve();
        }
      });
    });

    // Read the generated PDF file
    if (!fs.existsSync(tempPdfPath)) {
      throw new Error('Converted PDF file was not generated by Python.');
    }
    const pdfBuffer = await fs.promises.readFile(tempPdfPath);

    // Clean up temp files asynchronously
    fs.promises.unlink(tempDocxPath).catch(err => console.error('Error deleting temp DOCX:', err));
    fs.promises.unlink(tempPdfPath).catch(err => console.error('Error deleting temp PDF:', err));

    // Return PDF file binary response
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename.replace(/\.docx$/i, '')}.pdf"`,
      },
    });

  } catch (error: any) {
    console.error('Word to PDF Server Error:', error);
    return NextResponse.json({ error: error.message || 'Failed to convert Word document.' }, { status: 500 });
  }
}
